In [19]:
import pandas as pd
import seaborn as sns
import numpy as np

# Modelling

In [4]:
df = pd.read_csv('FINAL_DATAFRAME.csv')

In [5]:
df.head()

Unnamed: 0            id        date      time username  \
0           0  1.045203e+18  2018-09-27  06:47:22    10mgp   
1           1  1.036687e+18  2018-09-03  18:48:27    10mgp   
2           2  1.028857e+18  2018-08-13  04:15:16    10mgp   
3           3  1.017129e+18  2018-07-11  19:30:04    10mgp   
4           4  1.013736e+18  2018-07-02  10:45:58    10mgp   

                                               tweet  \
0  ['sure', 'luci', 'couldnt', 'miss', 'see', 'sp...   
1  ['darbaarbyabdul', 'guy', 'close', 'tri', 'pho...   
2  ['british', 'airway', 'safeti', 'lucki', 'serv...   
3  ['ive', 'enter', 'autotradergo', 'chanc', 'win...   
4         ['becci', 'sent', 'ongo', 'issu', 'thank']   

                                           mentions              hashtags  \
0  ['lucylucyprior', 'xrailgroup', 'transcityrail']                   NaN   
1                                ['darbaarbyabdul']                   NaN   
2        ['johnmsv', 'emirates', 'british_airways']                   NaN   
3                                               NaN  ['#autotradergoals']   
4                                  ['landrover_uk']                   NaN   

                                              topics         0     ...      \
0  {0: 0.0100580305, 1: 0.0100580305, 2: 0.228744...  0.010058     ...       
1      {1: 0.12951413, 2: 0.30384994, 8: 0.50829476}  0.000000     ...       
2  {0: 0.15713021, 1: 0.15714662, 2: 0.014292412,...  0.157130     ...       
3  {0: 0.15712872, 1: 0.15715624, 2: 0.014287142,...  0.157129     ...       
4  {0: 0.020004185, 1: 0.21999583, 2: 0.020004185...  0.020004     ...       

          6         7         8         9  sentiment            Timestamp  \
0  0.010058  0.010058  0.010060  0.110585   0.500000  2018-09-27 06:47:22   
1  0.000000  0.000000  0.508295  0.000000  -0.085185  2018-09-03 18:48:27   
2  0.014292  0.300065  0.014292  0.014292   0.333333  2018-08-13 04:15:16   
3  0.157153  0.157131  0.014290  0.014287   0.600000  2018-07-11 19:30:04   
4  0.020004  0.020004  0.020007  0.220022   0.000000  2018-07-02 10:45:58   

   DayOfWeek  Month  Hour  sent_class  
0          3      9     6           2  
1          0      9    18           1  
2          0      8     4           2  
3          2      7    19           2  
4          0      7    10           1  

[5 rows x 25 columns]

In [6]:
af = df[['id', 'username', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'DayOfWeek', 'Month', 'Hour', 'sentiment']]

In [7]:
af.head()

id username         0         1         2         3         4  \
0  1.045203e+18    10mgp  0.010058  0.010058  0.228744  0.487173  0.113148   
1  1.036687e+18    10mgp  0.000000  0.129514  0.303850  0.000000  0.000000   
2  1.028857e+18    10mgp  0.157130  0.157147  0.014292  0.014292  0.157099   
3  1.017129e+18    10mgp  0.157129  0.157156  0.014287  0.014288  0.299989   
4  1.013736e+18    10mgp  0.020004  0.219996  0.020004  0.419946  0.020008   

          5         6         7         8         9  DayOfWeek  Month  Hour  \
0  0.010058  0.010058  0.010058  0.010060  0.110585          3      9     6   
1  0.000000  0.000000  0.000000  0.508295  0.000000          0      9    18   
2  0.157097  0.014292  0.300065  0.014292  0.014292          0      8     4   
3  0.014289  0.157153  0.157131  0.014290  0.014287          2      7    19   
4  0.020004  0.020004  0.020004  0.020007  0.220022          0      7    10   

   sentiment  
0   0.500000  
1  -0.085185  
2   0.333333  
3   0.600000  
4   0.000000

In [8]:
import matplotlib.pyplot as plt

In [2]:
kf =  pd.read_csv('FINAL_DATAFRAME_CLASS.csv')

In [3]:
kf.drop(['Unnamed: 0'], axis=1, inplace=True)

In [4]:
kf.head()

id username         0         1         2         3         4  \
0  1.045203e+18    10mgp  0.010058  0.010058  0.228744  0.487173  0.113148   
1  1.036687e+18    10mgp  0.000000  0.129514  0.303850  0.000000  0.000000   
2  1.028857e+18    10mgp  0.157130  0.157147  0.014292  0.014292  0.157099   
3  1.017129e+18    10mgp  0.157129  0.157156  0.014287  0.014288  0.299989   
4  1.013736e+18    10mgp  0.020004  0.219996  0.020004  0.419946  0.020008   

          5         6         7         8         9  DayOfWeek  Month  Hour  \
0  0.010058  0.010058  0.010058  0.010060  0.110585          3      9     6   
1  0.000000  0.000000  0.000000  0.508295  0.000000          0      9    18   
2  0.157097  0.014292  0.300065  0.014292  0.014292          0      8     4   
3  0.014289  0.157153  0.157131  0.014290  0.014287          2      7    19   
4  0.020004  0.020004  0.020004  0.020007  0.220022          0      7    10   

   sentiment  sent_class  
0   0.500000           2  
1  -0.085185           1  
2   0.333333           2  
3   0.600000           2  
4   0.000000           1

In [9]:
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

In [10]:
X = kf[['username', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'DayOfWeek', 'Month', 'Hour']]
X = pd.get_dummies(X)

In [11]:
ss = StandardScaler()
X = pd.DataFrame(ss.fit_transform(X), columns=X.columns)
# I recognize here that I should've scaled after train test split.

C:\Users\mort8k\Anaconda3\envs\capstone_v1\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\mort8k\Anaconda3\envs\capstone_v1\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [12]:
y = kf[['sentiment']]

In [13]:
yc = kf[['sent_class']]

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, yc_train, yc_test = train_test_split(X,yc,test_size=0.2)

In [ ]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 5, 5))

clf.fit(X_train, yc_train)                         
clf.score(X_train, yc_train), clf.score(X_test, yc_test)    

/Users/LujFel/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [17]:
def one_hot_encoder(array):
    unique_values, indices = np.unique(array, return_inverse=True)
    print(unique_values)
    print(indices)
    one_hot_encoded_data = np_utils.to_categorical(indices, len(unique_values))
    return one_hot_encoded_data

In [21]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D
from keras.utils import np_utils

In [22]:
X.shape

(376949, 442)

In [26]:
yc_train_encoded = one_hot_encoder(yc_train)

[0 1 2]
[1 1 1 ... 0 1 2]


In [48]:
yc_test_encoded = one_hot_encoder(yc_test)

[0 1 2]
[2 1 0 ... 2 1 1]


In [81]:
model = Sequential()
model.add(Dense(128, input_shape=(442,), name='Input_Layer', activation='relu'))
model.add(Dense(256, activation='relu'))
# model.add(Dense(64, activation='relu'))
model.add(Dense(3, name='Output_Layer', activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input_Layer (Dense)          (None, 128)               56704     
_________________________________________________________________
dense_22 (Dense)             (None, 256)               33024     
_________________________________________________________________
Output_Layer (Dense)         (None, 3)                 771       
Total params: 90,499
Trainable params: 90,499
Non-trainable params: 0
_________________________________________________________________


In [82]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [83]:
model.fit(X_train, yc_train_encoded, batch_size=None, epochs=30, steps_per_epoch=5)

Epoch 1/30
5/5 [==============================] - 7s 1s/step - loss: 0.9690 - acc: 0.5978
Epoch 2/30
5/5 [==============================] - 6s 1s/step - loss: 0.8942 - acc: 0.6369
Epoch 3/30
5/5 [==============================] - 6s 1s/step - loss: 0.8366 - acc: 0.6502
Epoch 4/30
5/5 [==============================] - 6s 1s/step - loss: 0.8160 - acc: 0.6543
Epoch 5/30
5/5 [==============================] - 6s 1s/step - loss: 0.8059 - acc: 0.6571
Epoch 6/30
5/5 [==============================] - 6s 1s/step - loss: 0.7960 - acc: 0.6577
Epoch 7/30
5/5 [==============================] - 6s 1s/step - loss: 0.7923 - acc: 0.6596
Epoch 8/30
5/5 [==============================] - 6s 1s/step - loss: 0.7873 - acc: 0.6601
Epoch 9/30
5/5 [==============================] - 6s 1s/step - loss: 0.7857 - acc: 0.6615
Epoch 10/30
5/5 [==============================] - 6s 1s/step - loss: 0.7834 - acc: 0.6619
Epoch 11/30
5/5 [==============================] - 6s 1s/step - loss: 0.7822 - acc: 0.6623
Epoch 12

In [84]:
model.evaluate(X_test, yc_test_encoded)

75390/75390 [==============================] - 5s 60us/step


[0.7742246117985901, 0.6697705265918766]

In [89]:
X_test.shape

(75390, 442)

In [85]:
model.save('lujain_model.h5')